In [1]:
import numpy as np
import pandas as pd

In [2]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [3]:
a = np.array([1,4,6])
b = np.array([2,3,4])
c = a +b
c

array([ 3,  7, 10])

In [4]:
g = a.dot(b)

In [5]:
g

38

In [6]:
s = 5

In [7]:
c = a*s
c

array([ 5, 20, 30])

In [9]:
from numpy.linalg import norm


In [11]:
l1 = norm(a,1)
l1

11.0